### ISSUE TITLE
paper “Causal Navigation by Continuous-time Neural Networks”

### ISSUE THREAD

**Issue by beGraced-zhang** [mlech26l/ncps#33]
Hi, @mlech26l 
           I am reading paper “Causal Navigation by Continuous-time Neural Networks” another great job for your team published in NeurIPS2021. GitHub URLs " https://github.com/mit-drl/deepdrone" for code and data are provided in the paper，but when I visit this url I get the message of 404. I am able to access GitHub normally. So I want to know what happened.  can you provide the correct URL about code?
          Thanks.

**Comment by mlech26l** [comment]
Hi @ZhangMengEnAPI 

I also get a 404.
I think @raminmh knows what happened with the repo.

**Comment by ZhangMengEnAPI** [comment]
@raminmh Could you do me a favor?

**Comment by raminmh** [comment]
Certainly. The repo is currently being used for a couple of other projects. I will release the code publicly again within the next 3 weeks. Stay tuned!

**Comment by Niqnil** [comment]
https://github.com/mit-drl/deepdrone is no longer public? Forever?

**Comment by MalekWahidi** [comment]
> Certainly. The repo is currently being used for a couple of other projects. I will release the code publicly again within the next 3 weeks. Stay tuned!

Any updates?

**Comment by noorchauhan** [comment]
Hie Dr. Hasani @raminmh , I also am looking foward to work on the repository [deepdrone](https://github.com/mit-drl/deepdrone) , if you could open the access it would be helpful
