### ISSUE TITLE
Data icra2020_imitation_data

### ISSUE THREAD

**Issue by huyenng308** [mlech26l/ncps#35]
Thank you so much for your incredible work. But I have questions related to data from your repository.
Could you please explain more about the data `https://github.com/mlech26l/icra_lds/raw/master/icra2020_imitation_data_packed.npz`?
How did you do to collect data? Because in google collaboratory, you said that 

> Input data is obtained from a [Sick LMS 1xx laser rangefinder (LiDAR)](https://www.sick.com/ag/en/detection-and-ranging-solutions/2d-lidar-sensors/lms1xx/c/g91901) mounted on the robot. Output variable is the steering direction as a variable in the range [-1,+1], i.e., -1 corresponding to turning left, 0 going straight, and +1 to turning right. Supervised training data was collected by manually steering the robot around the obstacles on 29 different tracks.

However, in closed issue #5, you said that the dataset generated by the active test runs is available for download from repository. It makes me confused about this dataset, is it collected by from a Sick LMS 1xx laser rangefinder (LiDAR) or generated by your algorithm ? 

Besides, in these following shape of dataset, I understand there are 678 samples with sequence of length 32. Could you please provide information about (541,1) of x_train? If I was not mistaken, 541 would be the number of features, so what is the information of these features?
```
x_train (678, 32, 541, 1)
y_train (678, 32, 1)
```

**Comment by mlech26l** [comment]
HI @huyenng308 

The dataset in the file ```https://github.com/mlech26l/icra_lds/raw/master/icra2020_imitation_data_packed.npz``` is from a different paper (this [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9196608) to be precise) and was collected by manually controlling the mobile robot to navigate it through a course of obstacles. 

The dataset dimension ```(678, 32, 541, 1)``` are:

- 678 samples (=trajectories)
- 32 is the sequence lengths
 - 541 is the number of casted LiDAR rays (= number of input features)
 - 1 each LiDAR ray returns a single value measuring the distance of the robot to the nearest object in this direction (each LiDAR ray is casted in a different direction)

The labels ```(678, 32, 1)``` are
- 678 samples (=trajectories)
- 32 is the sequence lengths
- The direction in which the robot should navigate (e.g., a continuous value representing left to right steering)


The dataset in closed issue #5 is from the [NCP paper](https://publik.tuwien.ac.at/files/publik_292280.pdf) and concerns the steering of a car and contains both manually controlled trajectories (for training) and trajectories from the algorithm (for testing).

**Comment by huyenng308** [comment]
Thank you for your very detailed explanation. 

Could you please tell me where to download dataset from repository and please share me the large dataset (193GB)? I would like to access both of them.  My email is s219829r@st.go.tuat.ac.jp

Thank you so much for your excellent work. I am working on Liquid Time-Constant Networks and it would be really interesting when applying to the task of steering.

**Comment by mlech26l** [comment]
Hi @huyenng308 
I have sent you an email.
