### ISSUE TITLE
problem loading tensorflow models

### ISSUE THREAD

**Issue by PolKul** [mlech26l/ncps#36]
I'm using your example code from [here](https://ncps.readthedocs.io/en/latest/examples/tf_first_steps.html) I save the model using 
`model.save(model_dir)` but when loading it with the `model = keras.models.load_model(model_dir)` I get an error: `TypeError: ('Keyword argument not understood:', 'adjacency_matrix')`

**Comment by mlech26l** [comment]
Model serialization is currently not supported.
Can you try saving and restoring only the weights via [model.save_weights](https://keras.io/api/models/model_saving_apis/#saveweights-method) and [model.load_weights](https://keras.io/api/models/model_saving_apis/#loadweights-method)?
