### ISSUE TITLE
关于文中整个网络框架的解读

### ISSUE THREAD

**Issue by wyl121** [mlech26l/ncps#42]
Hello！In your article Neural circuit policies enabling auditable autonomy, you give the number of units in the last fully-connected layer of the convolution head as one, which does not match the network structure diagram in the article with 32 sensory neurons, I would like to know if my understanding of the article is off.Hope to get your advice.

**Comment by mlech26l** [comment]
The layer of the convolution head has 8 filters in the last layer. These 8 features maps are then mapped per-channel via linear layers to obtain 8×4=32 latent features serving as sensory inputs to the RNN compartment.

**Comment by wyl121** [comment]
Thank you very much for your guidance, but I am still a bit confused for the following reasons:
    This is the parameter information of the feedforward CNN layer given in your expanded data in the text：
conv2d                   F:24,K:5,S:2
conv2d                   F:36,K:5,S:2
conv2d                   F:48,K:3,S:2
conv2d                   F:64,K:3,S:1
conv2d                   F:64,K:3,S:1
Flatten
Dropout                       &1
Fully-connected       U:1000,ReLU
Dropout                       &2
Fully-connected        U:1000,ReLU
Dropout                        &3
Fully-connected        U:1,Identity
I can't connect this to what you said above, so I'd like to get your feedback. I'm a beginner in this field, if you could please guide me to a more detailed description of the entire network framework, I hope this question will not make you feel presumptuous, thank you very much!

**Comment by mlech26l** [comment]
This is the CNN. It's a different network than the RNNs. 
The RNNs consist of a convolutional head with 32 units in the last layer, followed by an RNN (e.g., an LSTM or NCP).

The CNN consists of the layers you mentioned above (conv2d, flatten, dropout and fully connected layers)

**Comment by wyl121** [comment]
Thanks for your reply, I understand it in general. Your work has inspired me a lot and I am trying to do something new with such a network, thank you very much!
