### ISSUE TITLE
Example of stacking LTC with convolutional layers on pytorch version

### ISSUE THREAD

**Issue by wyl121** [mlech26l/ncps#51]
Hello!Thank you for having such a great work for many beginners like me to learn, recently I am using pytorch framework to build LTC model, but I can never use convolutional layer and LTC well together, always report the error of data dimension mismatch makes me very distressed, hope to get a pytorch framework of convolutional layer and LTC stacking example, looking forward to your reply!

**Comment by mlech26l** [comment]
Hello, 
The Atari behavior cloning tutorial contains an example of convolutional layers stacked with an LTC/CfC:
https://ncps.readthedocs.io/en/latest/examples/atari_bc.html

**Comment by wyl121** [comment]
Thank you very much for your help, I have benefited a lot!
