### ISSUE TITLE
Python gives anRuntime error when I try to send hidden state (hx) to the CfC model.

### ISSUE THREAD

**Issue by Keremm1** [mlech26l/ncps#62]
### Errors
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

**when loss.backward(retain_graph=True)**  :: 
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [17, 10]], which is output 0 of AsStridedBackward0, is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**when with torch.autograd.set_detect_anomaly(True) ::**
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [17, 10]], which is output 0 of AsStridedBackward0, is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

##**I did not add some datasets, preparations and variables to avoid confusion.**

```
network = Net()
optimizer = optim.SGD(network.parameters(), lr=learning_rate,
                      momentum=momentum)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)
        self.cfc = CfC(10, AutoNCP(28, 10))

    def forward(self, x, hx):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        x, hx = self.cfc(x, hx)
        return F.log_softmax(x), hx

def train(epoch):
    hx = None
    network.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        optimizer.zero_grad()
        output, hx = network(data, hx)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
              epoch, batch_idx * len(data), len(train_loader.dataset),
              100. * batch_idx / len(train_loader), loss.item()))
            train_losses.append(loss.item())
            train_counter.append(
              (batch_idx*64) + ((epoch-1)*len(train_loader.dataset)))

for epoch in range(1, n_epochs + 1):
    train(epoch)
```
### TraceBacks
:\Users\Lenovo\anaconda3\lib\site-packages\torch\autograd\__init__.py:173: UserWarning: Error detected in AddmmBackward0. Traceback of forward call that caused the error:
  File "c:\Users\Lenovo\Desktop\algos\test.py", line 104, in <module>
    train(epoch)
  File "c:\Users\Lenovo\Desktop\algos\test.py", line 74, in train
    output, hx = network(data, hx)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\Lenovo\Desktop\algos\test.py", line 55, in forward
    x, hx = self.cfc(x, hx)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ncps\torch\cfc.py", line 173, in forward
    h_out, h_state = self.rnn_cell.forward(inputs, h_state, ts)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ncps\torch\wired_cfc_cell.py", line 102, in forward
    h, _ = self._layers[i].forward(inputs, h_state[i], timespans)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ncps\torch\cfc_cell.py", line 161, in forward
    t_b = self.time_b(x)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
 (Triggered internally at  C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\torch\csrc\autograd\python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "c:\Users\Lenovo\Desktop\algos\test.py", line 104, in <module>
    train(epoch)
  File "c:\Users\Lenovo\Desktop\algos\test.py", line 76, in train
    loss.backward(retain_graph=True)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

**Comment by Keremm1** [comment]
i solved this problem with replacing 
`h_state, c_state = hx if self.use_mixed else (hx, None)`
by
`h_state, c_state = hx.clone().detach(), None \n
h_state.requires_grad_(True)`

**Comment by by90** [comment]
but, merge it now?
